AllCops:
  Exclude:
    # Because we don't use this test suite at the moment.
    - 'spec/ui_test.rb'
    # Because these are vendor files.
    - 'node_modules/**/*'

Metrics/AbcSize:
  Exclude:
    # TODO
    - 'lib/sequenceserver.rb'
    - 'lib/sequenceserver/database.rb'
Metrics/MethodLength:
  # Because 15 lines in a method is just about as good as 10 (default). And we
  # have a couple that can't be helped.
  Max: 15
  Exclude:
    # TODO:
    - 'lib/sequenceserver.rb'
Metrics/BlockNesting:
  Exclude:
    # TODO:
    #   Fix in bin/sequenceserver and re-enable.
    - 'bin/sequenceserver'

Lint/Eval:
  # Used only once. Is rather safe.
  Enabled: false

Style/UnlessElse:
  # TODO:
  #   Fix in bin/sequenceserver and re-enable.
  Enabled: false
Style/ClassAndModuleCamelCase:
  Exclude:
    # TODO:
    #   Revisit later.
    - 'lib/sequenceserver/exceptions.rb'
Style/Lambda:
  Exclude:
    # Because we support 1.8.7.
    - '**/*.rb'
Style/EachWithObject:
  Exclude:
    # Because we support 1.8.7.
    - '**/*.rb'
Style/HashSyntax:
    # Because we support 1.8.7.
  EnforcedStyle: hash_rockets
