language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2

before_install:
  - wget -c "ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.27/ncbi-blast-2.2.27+-x64-linux.tar.gz" && tar xvf ncbi-blast-2.2.27+-x64-linux.tar.gz && export PATH="./ncbi-blast-2.2.27+/bin:$PATH"
  - gem install bundler
